# .readthedocs.yaml

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Install dependencies via pip
python:
  install:
    - requirements: requirements.txt  # Use the requirements.txt file for dependencies
    - requirements: docs/requirements.txt  # For Sphinx and other doc-related dependencies

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
