duration: 10800
ip_addresses:
- 8.8.8.8
ping_interval: 1
latency_threshold: 200.0
no_aggregation: false
no_segmentation: false
results_folder: results
log_folder: logs
file: null
clear: false
clear_results: false
clear_logs: false
'yes': false
